const app=document.querySelector("#app");let screen="splash",focus=0,user="Andrew",tab=0,toast="";
const tabs=["Home","Games","Media","Store","Library","Settings"];
const data={
Home:[["🎮","Continue","Your recent games"],["▶","Media","Streaming services"],["◫","Store","Discover apps"],["⌘","Library","Installed apps"]],
Games:[["🎮","Steam Library","Existing Steam games"],["☁","Cloud Gaming","Web gaming services"],["🕹","Emulation","Retro library"],["＋","Add Game","Import a title"]],
Media:[["N","Netflix","Web app"],["▶","YouTube","Web app"],["P","Prime Video","Web app"],["♫","Spotify","Web app"]],
Store:[["▣","Flathub","Linux apps"],["▶","Media Pack","Streaming services"],["🕹","Gaming Tools","Launchers & utilities"],["⌘","Omarchy","Selected packages"]],
Library:[["▶","Media","Installed services"],["🎮","Games","Detected titles"],["▣","Applications","Installed apps"],["★","Favorites","Pinned items"]],
Settings:[["🎮","Controllers","Pair & configure"],["◉","Display","Deck & TV"],["↻","Updates","Check GitHub"],["♙","Profiles","Manage users"]]};
const profiles=["Andrew","Guest","+ Add profile"];
function render(){
 if(screen==="splash"){app.innerHTML='<section class="screen splash"><div class="logo">Oma<em>Steam</em>Deck</div><div class="kicker">powered by omarchy</div><div class="loader"></div></section>';setTimeout(()=>{screen="profiles";focus=0;render()},1600);return}
 if(screen==="profiles"){app.innerHTML='<section class="screen profiles"><div class="kicker">OmaSteamDeck</div><h1>Who’s playing?</h1><div class="profile-row">'+profiles.map((p,i)=>'<button class="profile '+(i===focus?"focused":"")+'"><span class="kicker">profile</span><b>'+p+'</b></button>').join("")+'</div><div class="footer">D-pad / stick move · A / Enter select</div></section>';return}
 const items=data[tabs[tab]];app.innerHTML='<section class="screen"><header><div><div class="kicker">OmaSteamDeck</div><h1>'+user+'</h1></div><div class="status">STEAM DECK · HANDHELD</div></header><nav class="tabs">'+tabs.map((t,i)=>'<button class="navbtn '+(i===tab?"active":"")+'">'+t+'</button>').join("")+'</nav><div class="hero"><div class="kicker">'+tabs[tab]+'</div><h2>'+(tab===0?"Your space. Ready to play.":tabs[tab])+'</h2><p>'+(tab===2?"Movies, music and streaming in one place.":tab===3?"One store. Multiple Linux ecosystems underneath.":tab===5?"Make OmaSteamDeck yours.":"Controller-first. Fast. Quiet.")+'</p></div><div class="rowtitle"><h3>'+(tab===0?"For you":"Browse")+'</h3><span>A SELECT · B BACK · LB/RB SECTIONS</span></div><div class="cards">'+items.map((x,i)=>'<button class="card '+(i===focus?"focused":"")+'"><span class="art">'+x[0]+'</span><span><b>'+x[1]+'</b><br><small>'+x[2]+'</small></span></button>').join("")+'</div><div class="footer">OmaSteamDeck v0.1 · Prototype build</div></section>'+(toast?'<div class="toast">'+toast+'</div>':"")
}
function move(d){const n=screen==="profiles"?profiles.length:data[tabs[tab]].length;focus=(focus+d+n)%n;render()}
function changeTab(d){if(screen!=="home")return;tab=(tab+d+tabs.length)%tabs.length;focus=0;render()}
function select(){if(screen==="profiles"&&focus<2){user=profiles[focus];screen="home";focus=0;render();return}if(screen==="home"){const item=data[tabs[tab]][focus][1];if(item==="Updates"){toast="Update check will use GitHub releases in the packaged build.";render();setTimeout(()=>{toast="";render()},2500)}else{toast=item+" selected";render();setTimeout(()=>{toast="";render()},1200)}}}
function back(){if(screen==="home"){screen="profiles";focus=0;render()}}
addEventListener("keydown",e=>{if(["ArrowRight","ArrowDown"].includes(e.key))move(1);if(["ArrowLeft","ArrowUp"].includes(e.key))move(-1);if(e.key==="Enter")select();if(e.key==="Escape")back();if(e.key==="PageDown")changeTab(1);if(e.key==="PageUp")changeTab(-1)});
let last=0;function poll(){const g=navigator.getGamepads?.()[0];if(g&&Date.now()-last>170){if(g.buttons[0]?.pressed){select();last=Date.now()}else if(g.buttons[1]?.pressed){back();last=Date.now()}else if(g.buttons[5]?.pressed){changeTab(1);last=Date.now()}else if(g.buttons[4]?.pressed){changeTab(-1);last=Date.now()}else if(g.buttons[15]?.pressed||g.axes[0]>.65){move(1);last=Date.now()}else if(g.buttons[14]?.pressed||g.axes[0]<-.65){move(-1);last=Date.now()}}requestAnimationFrame(poll)}render();poll();